/**
 * Vite plugin: emit public/firebase-messaging-sw.js with VITE_FIREBASE_* baked in.
 * Service workers cannot read import.meta.env, so we regenerate this file on startup/build.
 */
import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

const SW_NAME = 'firebase-messaging-sw.js'

function buildSwSource(env: Record<string, string>): string {
  const apiKey =
    (env.VITE_FIREBASE_API_KEY || '').trim() || 'AIzaSyDXmSVhx9pMdSFy6JxG5wM_UI1e4J3AxNw'
  const authDomain =
    (env.VITE_FIREBASE_AUTH_DOMAIN || '').trim() || 'goldstandard-dcca4.firebaseapp.com'
  const projectId = (env.VITE_FIREBASE_PROJECT_ID || '').trim() || 'goldstandard-dcca4'
  const storageBucket =
    (env.VITE_FIREBASE_STORAGE_BUCKET || '').trim() ||
    'goldstandard-dcca4.firebasestorage.app'
  const messagingSenderId =
    (env.VITE_FIREBASE_MESSAGING_SENDER_ID || '').trim() || '277505358501'
  const appId =
    (env.VITE_FIREBASE_APP_ID || '').trim() || '1:277505358501:web:96b54751f8a302e69dab4c'

  return `/* Auto-generated by vite — do not edit by hand. */
/* eslint-disable no-restricted-globals */
importScripts('https://www.gstatic.com/firebasejs/11.10.0/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/11.10.0/firebase-messaging-compat.js')

firebase.initializeApp({
  apiKey: ${JSON.stringify(apiKey)},
  authDomain: ${JSON.stringify(authDomain)},
  projectId: ${JSON.stringify(projectId)},
  storageBucket: ${JSON.stringify(storageBucket)},
  messagingSenderId: ${JSON.stringify(messagingSenderId)},
  appId: ${JSON.stringify(appId)},
})

const messaging = firebase.messaging()

messaging.onBackgroundMessage((payload) => {
  const title =
    (payload.notification && payload.notification.title) ||
    (payload.data && payload.data.title) ||
    'Gold Standard'
  const body =
    (payload.notification && payload.notification.body) ||
    (payload.data && payload.data.body) ||
    ''
  const url =
    (payload.data && (payload.data.url || payload.data.deep_link)) || '/'
  const icon =
    (payload.notification && payload.notification.icon) ||
    '/favicons/android-chrome-192x192.png'

  return self.registration.showNotification(title, {
    body,
    icon,
    badge: '/favicons/favicon-32x32.png',
    data: { url, ...(payload.data || {}) },
  })
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const target = (event.notification.data && event.notification.data.url) || '/'
  const absolute = String(target).startsWith('http')
    ? target
    : new URL(target, self.location.origin).href

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          client.navigate?.(absolute)
          return client.focus()
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(absolute)
      }
      return undefined
    }),
  )
})
`
}

export function firebaseMessagingSwPlugin(): Plugin {
  let root = process.cwd()
  let outDir = 'dist'

  const write = (env: Record<string, string>, destDir: string) => {
    const dest = path.join(destDir, SW_NAME)
    fs.mkdirSync(destDir, { recursive: true })
    fs.writeFileSync(dest, buildSwSource(env), 'utf8')
  }

  return {
    name: 'firebase-messaging-sw',
    configResolved(config) {
      root = config.root
      outDir = path.resolve(config.root, config.build.outDir)
    },
    buildStart() {
      const env = { ...process.env } as Record<string, string>
      // Vite loads .env into process via loadEnv in defineConfig — also read public dir for dev.
      write(env, path.join(root, 'public'))
    },
    closeBundle() {
      const env = { ...process.env } as Record<string, string>
      write(env, outDir)
    },
  }
}
